### ISSUE TITLE
Github Actions Workflow Fails for Android 32-bit Builds `ld: error: cannot open crtbegin_so.o: No such file or directory`

### ISSUE THREAD

**Issue by Atlinx** [godotengine/godot-cpp-template#30]
### Godot version

4.2

### godot-cpp version

4.2 branch [4320c62c]

### System information

Windows 11

### Issue description

When using the GitHub actions to build my gd-extension, I get the following error for android 32-bit builds: `ld: error: cannot open crtbegin_so.o: No such file or directory`

Here's the full error:
```
ld: error: cannot open crtbegin_so.o: No such file or directory
ld: error: unable to find library -lc++
ld: error: cannot open crtend_so.o: No such file or directory
clang-14: error: linker command failed with exit code 1 (use -v to see invocation)
scons: *** [bin/better-terrain-pp/libgdbetterterrainpp.android.template_release.x86_32.so] Error 1
scons: building terminated because of errors.
```

Here's my gd-extension repository: https://github.com/Atlinx/better-terrain-gde

**Comment by paddy-exe** [comment]
There seems to be an issue with the Android dependencies. https://github.com/godotengine/godot-cpp-template/pull/33 possibly fixes this

**Comment by Atlinx** [comment]
Unfortunately the error still persists even with the PR :(
