### ISSUE TITLE
Node.js 16 actions are deprecated.

### ISSUE THREAD

**Issue by Atlinx** [godotengine/godot-cpp-template#31]
### Godot version

v4.2

### godot-cpp version

Latest

### System information

Windows 11

### Issue description

The github actions workflow uses Node.js 16 actions, which are deprecated. All the deprecated packages should have newer versions that use Node.js 20, so you can fix this by using the latest versions of every package.

**Comment by paddy-exe** [comment]
Hey there, could you please provide the names of the actions that would be outdated?
