### ISSUE TITLE
[Actions] Using the actions in this example I only receive old files

### ISSUE THREAD

**Issue by scriptsengineer** [godotengine/godot-cpp-template#36]
### Godot version

v4.2.2.stable.official [15073afe3]

### godot-cpp version

v4.2.2.stable.official [98c143a4]

### System information

Windows 11

### Issue description

I'm using this action template for my plugin that is Godot asset lib
https://github.com/expressobits/inventory-system/tree/gdextension

However, I always receive old files in the result, in general the Linux and Windows dlls are old, but notably I receive some rubbish from previous builds, for example I disabled the compilation of dlls with double and I still receive them in the final zip.

Note: in my repo I tested disabling the "merge" step and I receive several zips of libs that are not alone but always updated and together with old versions from other platforms.
Example: android lib with old windows files.
![image](https://github.com/user-attachments/assets/e31bb208-89f0-4989-966c-4f07bc9b27ce)

**Comment by paddy-exe** [comment]
You have committed binary files in your binary folders for windows, mac, iOS and web.

**Comment by scriptsengineer** [comment]
It solved my problem thank you @paddy-exe!
