### ISSUE TITLE
Add ways to modify the output executable name

### ISSUE THREAD

**Issue by fire** [godotengine/godot-cpp-template#56]
### Godot version

v4.4

### godot-cpp version

https://github.com/godotengine/godot-cpp/tree/fbbf9ec4efd8f1055d00edb8d926eef8ba4c2cce

### System information

Windows 11

### Issue description

Document ways to modify the output gdextension library name without hacking the SCsub.

**Comment by dsnopek** [comment]
> Document ways to modify the output gdextension library name without hacking the SCsub.

I feel like modifying the `SConstruct` is the right way to change the library name, though. This isn't something the user needs to customize - a particular project is going to use a particular hard-coded name.

**Comment by paddy-exe** [comment]
I concur. I would therefor close this issue.
